-- project table

ALTER TABLE IF EXISTS project
ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
ALTER COLUMN last_updated_at SET DATA TYPE TIMESTAMP;

-- user table

ALTER TABLE IF EXISTS "user"
ALTER COLUMN created_at SET DATA TYPE TIMESTAMP,
ALTER COLUMN last_updated_at SET DATA TYPE TIMESTAMP;
